/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("springtest.java-application-conventions")
    id("org.springframework.boot") version "2.5.4"
}

dependencies {
    implementation("org.apache.commons:commons-text:1.10.0")
    implementation("org.springframework.boot:spring-boot-starter-web:3.0.5")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:3.0.5")
    implementation("org.springframework.boot:spring-boot-autoconfigure:3.0.5")
    implementation(project(":utilities"))
}
repositories {
    mavenCentral()
    mavenLocal()
}

application {
    // Define the main class for the application.
    mainClass.set("springtest.app.App")
}
